import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, it, expect } from "vitest";
import {
  CLIENT_ROWS,
  CLIENTS,
  SETS_PER_HALF,
  WIDEST_SUPPORTED_VIEWPORT,
  setWidth,
} from "@/components/landing/clients";

const here = dirname(fileURLToPath(import.meta.url));
const publicClients = join(here, "../../../public/clients");
const en = JSON.parse(readFileSync(join(here, "../../messages/en.json"), "utf8"));
const ar = JSON.parse(readFileSync(join(here, "../../messages/ar.json"), "utf8"));

/**
 * Read a PNG's true pixel dimensions off its IHDR chunk.
 *
 * Hand-parsed rather than pulled from an image library: the whole point of the
 * check is to compare the manifest against the BYTES ON DISK, and reaching for
 * a dependency to read eight big-endian bytes would add a package to the build
 * for a header every PNG is required to open with.
 */
function pngSize(path: string): [number, number] {
  const buf = readFileSync(path);
  const signature = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  if (!buf.subarray(0, 8).equals(signature)) {
    throw new Error(`${path} is not a PNG`);
  }
  return [buf.readUInt32BE(16), buf.readUInt32BE(20)];
}

describe("the ticker loops without a visible gap", () => {
  it("fills more than the widest supported viewport with half a track", () => {
    // This is the whole correctness condition for a -50% marquee. Half the
    // track must cover the viewport, or the end of every cycle drags an empty
    // stretch across the screen — which is what two copies of four logos did:
    // a ~970px half against a 1440px laptop, so a third of the row was blank
    // for part of every loop.
    for (const row of CLIENT_ROWS) {
      const half = setWidth(row) * SETS_PER_HALF;
      expect(half).toBeGreaterThan(WIDEST_SUPPORTED_VIEWPORT);
    }
  });

  it("splits the logos into two rows that share nothing", () => {
    const [a, b] = CLIENT_ROWS;
    const overlap = a.filter((logo) => b.some((other) => other.key === logo.key));
    // Two rows scrolling against each other showing the same logo twice reads
    // as padding rather than as a client list.
    expect(overlap).toEqual([]);
    expect(a.length + b.length).toBe(CLIENTS.length);
  });
});

describe("every logo is a real, described asset", () => {
  const files = new Set(readdirSync(publicClients));

  it("points at a file that exists", () => {
    for (const logo of CLIENTS) {
      expect(files.has(logo.src.replace("/clients/", ""))).toBe(true);
    }
  });

  it("declares the asset's true intrinsic size", () => {
    /**
     * next/image reserves space from these numbers. If they disagree with the
     * file's real dimensions the row shifts as the images load, which is
     * exactly the CLS the width/height props exist to prevent.
     *
     * THIS USED TO READ THE SVG's `viewBox`. The wall is 31 raster PNGs now,
     * so that assertion had nothing left to parse — and an assertion that
     * quietly matches nothing is worse than no assertion, because the suite
     * still goes green and everyone reads that as the property holding. The
     * check follows the assets to their new format rather than retiring with
     * the old one: the numbers below are now generated by a script, which is
     * precisely the situation where a stale copy-paste goes unnoticed.
     */
    for (const logo of CLIENTS) {
      const file = logo.src.replace("/clients/", "");
      const [w, h] = pngSize(join(publicClients, file));
      expect(w, `${logo.key}: manifest says ${logo.width}w, file is ${w}w`).toBe(logo.width);
      expect(h, `${logo.key}: manifest says ${logo.height}h, file is ${h}h`).toBe(logo.height);
    }
  });

  it("gives every mark the same canvas height", () => {
    /**
     * The optical normalisation is BAKED INTO THE PIXELS: each mark is scaled
     * inside a canvas of one fixed height so that a square crest and a long
     * wordmark carry comparable visual weight at the same rendered height.
     * That only works while the canvases agree. One asset dropped in at its
     * own natural size renders at the same 44px as the rest and silently
     * breaks the balance for the whole row, with nothing to see in a diff.
     */
    const heights = new Set(CLIENTS.map((l) => l.height));
    expect([...heights], "every client logo canvas must be the same height").toHaveLength(1);
  });

  it("has an accessible name in both locales", () => {
    for (const messages of [en, ar]) {
      const alts = messages.landing.clients.logos as { key: string; alt: string }[];
      for (const logo of CLIENTS) {
        const entry = alts.find((a) => a.key === logo.key);
        expect(entry, `${logo.key} missing alt`).toBeTruthy();
        expect(entry!.alt.trim().length).toBeGreaterThan(0);
      }
    }
  });
});

describe("the invented companies cannot come back", () => {
  /**
   * A client wall is a factual claim about who a company has worked for, and
   * for three rounds this one carried eight companies that do not exist. That
   * was never an unfinished placeholder; it was a false statement on the front
   * page, and it is the single worst thing the content audit found.
   *
   * The names are kept here as a blocklist rather than deleted with the files.
   * They are the exact shape of the mistake — plausible, well-drawn, correctly
   * sized marks that fill a row — and the next person short of a logo will
   * reach for something just like them.
   */
  const INVENTED = [
    "northvale",
    "atlas-group",
    "meridian",
    "kawkab",
    "summit-co",
    "halcyon",
    "vertex",
    "rawabi",
  ];

  it("has no invented company left in public/clients", () => {
    /**
     * WAS A DELIBERATE FAILURE (`it.fails`) while the wall carried eight
     * companies that did not exist. The content audit replaced them with real
     * references from the wood factory's own client wall, three of which are
     * corroborated by a second document, so the gate has done its job and now
     * asserts the property instead of waiting for it.
     *
     * It stays as a guard rather than being deleted: these files are the one
     * place on the site where adding an asset makes a factual claim about a
     * third party, and re-adding a convenient placeholder to fill a gap in the
     * row is exactly the mistake that would go unnoticed.
     */
    const files = readdirSync(publicClients).map((f) => f.replace(/\.\w+$/, ""));
    expect(files.filter((f) => INVENTED.includes(f))).toEqual([]);
  });

  it("ships no mark that would render as a white box", () => {
    /**
     * WHAT THIS REPLACED, AND WHY IT IS NOT THE SAME CHECK. The old version
     * caught malformed SVG: "NESMA & PARTNERS" had been written with a raw
     * ampersand, which is not legal XML, so the browser dropped the document
     * and put a broken-image box in the middle of the wall. Nothing else found
     * it — the file existed, the manifest row was right, every test passed,
     * and it was visible only in a screenshot.
     *
     * There are no SVGs left, so that check now matches zero files. Rather
     * than delete the guard, it is pointed at the failure the RASTER wall can
     * actually have: a logo shipped with its background plate still attached.
     * Every source arrived as opaque artwork on white, and the build keys that
     * plate off; one file that skips the pipeline renders as a white rectangle
     * on a sand surface, in a row of marks that float. That is the modern
     * version of the same bug — an asset that is individually fine and wrong
     * in place, invisible to every check except looking at it.
     *
     * Colour type lives at byte 25 of a PNG: 6 is RGBA, 4 is grey+alpha, and
     * 3 (palette) can carry transparency in a tRNS chunk. Anything else has no
     * way to be transparent at all.
     */
    const bad: string[] = [];
    for (const file of readdirSync(publicClients)) {
      const buf = readFileSync(join(publicClients, file));
      if (!file.endsWith(".png")) {
        bad.push(`${file}: the wall is transparent PNGs only`);
        continue;
      }
      const colourType = buf[25];
      const hasAlpha =
        colourType === 6 || colourType === 4 || (colourType === 3 && buf.includes("tRNS"));
      if (!hasAlpha) {
        bad.push(`${file}: no alpha channel, so its plate is still attached`);
      }
    }
    expect(bad).toEqual([]);
  });
});
